### ISSUE TITLE
Encoding error when using guest execute

### ISSUE THREAD

**Issue by alinoancea** [sethmlarson/virtualbox-python#121]
##### ENVIRONMENT

- Operating System: Ubuntu 16.04
- Python version: 3.5.2
- VirtualBox version: 5.2.26
- VirtualBox SDK version: 5.2.26
- Location where VirtualBox SDK is installed: any
- pyvbox version: 1.3.2
- [x] Happens in latest `master` branch?

##### SUMMARY

When I'm trying to create a new process in a VM I get an encoding error
> TypeError: string argument without an encoding

##### STEPS TO REPRODUCE

Run this example
```
import virtualbox

vbox = virtualbox.VirtualBox()
session = virtualbox.Session()

vm = vbox.find_machine('Windows 10 x64')
vm.create_session(session=session)
session.unlock_machine()

progress = vm.launch_vm_process(session, 'gui')

progress.wait_for_completion()

guest = session.console.guest
with guest.create_session('username', 'password') as gs:
    process, stdout, stderr = gs.execute('cmd.exe', ['/c', 'ipconfig'])

    print(stdout)
```

##### EXPECTED RESULTS

The expected result should be the output from the ipconfig command which should return information about networking from the VM.

##### ACTUAL RESULTS

Traceback (most recent call last):
  File "./main.py", line 33, in <module>
    process, stdout, stderr = gs.execute('cmd.exe', ['/c', 'ipconfig'])
  File "/home/alin/.local/lib/python3.5/site-packages/virtualbox/library_ext/guest_session.py", line 89, in execute
    read_out(process, flags, stdout, stderr)
  File "/home/alin/.local/lib/python3.5/site-packages/virtualbox/library_ext/guest_session.py", line 55, in read_out
    e = bytes(process.read(2, 65000, 0))
TypeError: string argument without an encoding

## Possible solution
A posible solution could be changing in the guest_session.py file from bytes function to .encode. This resolved the problem in my case.

**Comment by alinoancea** [comment]
I made a [PR](https://github.com/sethmlarson/virtualbox-python/pull/122) with the changes, which I think it should be ok.
