### ISSUE TITLE
invalid start byte

### ISSUE THREAD

**Issue by sk3lk0** [sethmlarson/virtualbox-python#133]
##### ENVIRONMENT

- Operating System: manjaro
- Python version: Python 3.8.1
- VirtualBox version: 6.1
- VirtualBox SDK version:
- Location where VirtualBox SDK is installed: 
- virtualbox-python / pyvbox version: 2.0
- [ ] Happens in latest `master` branch?

##### SUMMARY
When i trying using 
process, stdout, stderr = gs.execute("C:\\Windows\\system32\\cmd.exe", ["/C", "tasklist"])
i have error

##### STEPS TO REPRODUCE

import virtualbox
vbox = virtualbox.VirtualBox()
session = virtualbox.Session()
vm = vbox.find_machine("avast")
session = vm.create_session()
gs = session.console.guest.create_session('user', '1')
gs.execute("C:\\Windows\\system32\\cmd.exe", ["/C", "tasklist"])

##### EXPECTED RESULTS
get tasklist info

##### ACTUAL RESULTS
python startvm_new.py 
Traceback (most recent call last):
  File "/home/user/PycharmProjects/untitled/venv/lib/python3.8/site-packages/virtualbox/library_base.py", line 201, in _call_method
    ret = method(*in_params)
  File "<XPCOMObject method 'read'>", line 3, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x88 in position 2: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "startvm_new.py", line 17, in <module>
    gs.execute("C:\\Windows\\system32\\cmd.exe", ["/C", "tasklist"]).decode(errors='replace')
  File "/home/user/PycharmProjects/untitled/venv/lib/python3.8/site-packages/virtualbox/library_ext/guest_session.py", line 90, in execute
    read_out(process, flags, stdout, stderr)
  File "/home/user/PycharmProjects/untitled/venv/lib/python3.8/site-packages/virtualbox/library_ext/guest_session.py", line 60, in read_out
    o = utils.to_bytes(process.read(1, 65000, 0))
  File "/home/user/PycharmProjects/untitled/venv/lib/python3.8/site-packages/virtualbox/library.py", line 20582, in read
    data = self._call("read",
  File "/home/user/PycharmProjects/untitled/venv/lib/python3.8/site-packages/virtualbox/library_base.py", line 192, in _call
    return self._call_method(method, in_p=in_p)
  File "/home/user/PycharmProjects/untitled/venv/lib/python3.8/site-packages/virtualbox/library_base.py", line 220, in _call_method
    raise errobj
virtualbox.library_base.VBoxError: 0xffffffff ('utf-8' codec can't decode byte 0x88 in position 2: invalid start byte)

**Comment by sethmlarson** [comment]
Sounds like there may be a Python version difference from where you're using `virtualbox` and where you installed `vboxapi`?

**Comment by sk3lk0** [comment]
vboxapi /usr/lib/python3.8/site-packages/vboxapi

[user@manjaro ~]$ whereis virtualbox
virtualbox: /usr/bin/virtualbox /usr/lib/virtualbox /usr/share/virtualbox

![image](https://user-images.githubusercontent.com/32999940/72783688-ba99ea00-3c2f-11ea-8973-90b8e31a4f71.png)

**Comment by sk3lk0** [comment]
so can you help me ?

**Comment by sethmlarson** [comment]
Unfortunately my time for this project is short and I don't even know where to start with debugging your system.

**Comment by sk3lk0** [comment]
its because i have russian letters in output

**Comment by sk3lk0** [comment]
it can solve problem export export PYTHONIOENCODING=utf-8
